sources:
  hn:
    base_url: "https://hacker-news.firebaseio.com/v0/topstories.json"
    min_articles: 1
    max_articles: 500
    base_single_url: "https://hacker-news.firebaseio.com/v0/item"
  pocket:
    base_url: "https://getpocket.com/v3/get"
    archive_url: "https://getpocket.com/v3/send"
    min_articles: 1
    max_articles: 100
    consumer_key: ""
    request_token: ""
    access_token: ""
default_source: "hn"
app_name: "raok"
db_port: 27000
blocked_keywords:
  - "bitcoin"
  - "chrome"
  - "webassembly"
review:
  types:
    - "unreviewed"
    - "interesting"
  default_type: "unreviewed"
  min_articles: 1
  max_articles: 25
list:
  types:
    - "sent"
    - "interesting"
  sorts:
    - "desc"
    - "asc"
  default_type: "interesting"
  default_sort: "desc"
  min_articles: 1
  max_articles: 25
push:
  min_articles: 1
  max_articles: 10
  chars_per_second: 1000
