sources:
  hn:
    base_url: "https://hacker-news.firebaseio.com/v0/topstories.json"
    min_articles: 1
    max_articles: 500
    base_single_url: "https://hacker-news.firebaseio.com/v0/item"
  pocket:
    base_url: "https://getpocket.com/v3/get"
    archive_url: "https://getpocket.com/v3/send"
    min_articles: 1
    max_articles: 100
    consumer_key: ""
    request_token: ""
    access_token: ""
default_source: "hn"
app_name: "raok"
db_port: 27000
