sources:
  hn:
    url: "https://hacker-news.firebaseio.com/v0/topstories.json"
    min_articles: 1
    max_articles: 500
  pocket:
    url: "https://getpocket.com/v3/get"
    min_articles: 1
    max_articles: 100
default_source: "hn"
