module.exports = {
	get_articles_content: require("./get_articles_content"),
	articles_to_file: require("./articles_to_file"),
	article_wrapper: require("./article_wrapper"),
	create_nav: require("./create_nav"),
	combine_files: require("./combine_files"),
	create_newspaper_header: require("./create_newspaper_header"),
	generate_title: require("./generate_title"),
	format_to_mobi: require("./format_to_mobi"),
	send_email: require("./send_email"),
	create_links_file: require("./create_links_file"),
	newspaper_to_zip: require("./newspaper_to_zip"),
	mark_as_read: require("./mark_as_read"),
	create_newspaper_entry: require("./create_newspaper_entry"),
};
